# Generated by Django 4.2.30 on 2026-10-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destinationimage_attraction_activity'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destinations',
            field=models.ManyToManyField(help_text='Select all destinations included in this journey.', related_name='tours', to='destinations.destination'),
        ),
    ]
