from django.contrib import admin

from .models import (
    Region,
    Destination,
    Attraction,
    Activity,
    DestinationImage,
)


@admin.register(Region)
class RegionAdmin(admin.ModelAdmin):
    """
    Admin configuration for Sikkim regions.

    Regions are used to organize destinations geographically.
    """

    # Shows useful information directly in the admin list.
    list_display = (
        "name",
        "destination_count",
    )

    # Makes large lists easier to filter/search.
    search_fields = (
        "name",
        "description",
    )

    # Automatically fills the slug from the region name.
    prepopulated_fields = {
        "slug": ("name",),
    }

    @admin.display(description="Destinations")
    def destination_count(self, obj):
        """
        Displays how many destinations belong to this region.

        Example:
        East Sikkim → 8
        West Sikkim → 5
        """
        return obj.destinations.count()


@admin.register(Destination)
class DestinationAdmin(admin.ModelAdmin):
    """
    Admin configuration for major Sikkim destinations.
    """

    # Important fields visible from the main admin list.
    list_display = (
        "name",
        "region",
        "featured",
        "is_active",
        "created_at",
        "updated_at",
    )

    # Useful filters when the database becomes large.
    list_filter = (
        "region",
        "featured",
        "is_active",
    )

    # Search across the fields an administrator is most likely to use.
    search_fields = (
        "name",
        "short_description",
        "description",
        "region__name",
    )

    # Automatically generates the slug while typing the destination name.
    prepopulated_fields = {
        "slug": ("name",),
    }

    # These fields can be changed directly from the list page.
    list_editable = (
        "featured",
        "is_active",
    )

    # Newest destinations appear first when appropriate.
    ordering = (
        "-created_at",
    )

    # Groups the form into logical sections so the admin page
    # remains easy to manage as the model grows.
    fieldsets = (
        (
            "Basic Information",
            {
                "fields": (
                    "name",
                    "slug",
                    "region",
                    "short_description",
                    "description",
                )
            },
        ),
        (
            "Travel Information",
            {
                "fields": (
                    "best_time_to_visit",
                    "how_to_reach",
                    "latitude",
                    "longitude",
                )
            },
        ),
        (
            "Destination Image",
            {
                "fields": (
                    "hero_image",
                )
            },
        ),
        (
            "Publishing",
            {
                "fields": (
                    "featured",
                    "is_active",
                )
            },
        ),
        (
            "Timestamps",
            {
                "fields": (
                    "created_at",
                    "updated_at",
                ),
                "classes": (
                    "collapse",
                ),
            },
        ),
    )

    # These fields are automatically generated by Django
    # and should not be manually edited.
    readonly_fields = (
        "created_at",
        "updated_at",
    )


@admin.register(Attraction)
class AttractionAdmin(admin.ModelAdmin):
    """
    Admin configuration for destination attractions.
    """

    list_display = (
        "name",
        "destination",
        "is_active",
        "created_at",
    )

    list_filter = (
        "destination",
        "is_active",
    )

    search_fields = (
        "name",
        "short_description",
        "description",
        "destination__name",
    )

    prepopulated_fields = {
        "slug": ("name",),
    }

    list_editable = (
        "is_active",
    )

    ordering = (
        "destination",
        "name",
    )

    fieldsets = (
        (
            "Attraction Information",
            {
                "fields": (
                    "destination",
                    "name",
                    "slug",
                    "short_description",
                    "description",
                )
            },
        ),
        (
            "Visitor Information",
            {
                "fields": (
                    "best_time_to_visit",
                    "entry_fee",
                )
            },
        ),
        (
            "Image",
            {
                "fields": (
                    "image",
                )
            },
        ),
        (
            "Publishing",
            {
                "fields": (
                    "is_active",
                )
            },
        ),
        (
            "Timestamps",
            {
                "fields": (
                    "created_at",
                    "updated_at",
                ),
                "classes": (
                    "collapse",
                ),
            },
        ),
    )

    readonly_fields = (
        "created_at",
        "updated_at",
    )


@admin.register(Activity)
class ActivityAdmin(admin.ModelAdmin):
    """
    Admin configuration for destination activities.
    """

    list_display = (
        "name",
        "destination",
        "difficulty",
        "is_active",
        "created_at",
    )

    list_filter = (
        "destination",
        "difficulty",
        "is_active",
    )

    search_fields = (
        "name",
        "short_description",
        "description",
        "destination__name",
    )

    prepopulated_fields = {
        "slug": ("name",),
    }

    list_editable = (
        "is_active",
    )

    ordering = (
        "destination",
        "name",
    )

    fieldsets = (
        (
            "Activity Information",
            {
                "fields": (
                    "destination",
                    "name",
                    "slug",
                    "short_description",
                    "description",
                )
            },
        ),
        (
            "Activity Details",
            {
                "fields": (
                    "duration",
                    "best_time",
                    "difficulty",
                )
            },
        ),
        (
            "Image",
            {
                "fields": (
                    "image",
                )
            },
        ),
        (
            "Publishing",
            {
                "fields": (
                    "is_active",
                )
            },
        ),
        (
            "Timestamps",
            {
                "fields": (
                    "created_at",
                    "updated_at",
                ),
                "classes": (
                    "collapse",
                ),
            },
        ),
    )

    # These fields are generated automatically by Django,
    # so they can be displayed but not edited.
    readonly_fields = (
        "created_at",
        "updated_at",
    )


@admin.register(DestinationImage)
class DestinationImageAdmin(admin.ModelAdmin):
    """
    Admin configuration for destination gallery images.
    """

    list_display = (
        "destination",
        "title",
        "display_order",
        "is_active",
        "created_at",
    )

    list_filter = (
        "destination",
        "is_active",
    )

    search_fields = (
        "destination__name",
        "title",
        "alt_text",
    )

    list_editable = (
        "display_order",
        "is_active",
    )

    ordering = (
        "destination",
        "display_order",
    )

    fieldsets = (
        (
            "Gallery Image",
            {
                "fields": (
                    "destination",
                    "image",
                    "title",
                    "alt_text",
                )
            },
        ),
        (
            "Gallery Settings",
            {
                "fields": (
                    "display_order",
                    "is_active",
                )
            },
        ),
        (
            "Created",
            {
                "fields": (
                    "created_at",
                ),
                "classes": (
                    "collapse",
                ),
            },
        ),
    )

    readonly_fields = (
        "created_at",
    )